# app config file (sample)
# you should follow the installation guide to configure the following fields
# (IMPORTANT) after your editing, the file name should be renamed to "config.yaml"

db_config:
  protocol: "tcp"            # Connection protocol, "tcp" is recommended and default
  host: "127.0.0.1"          # Database server host, e.g. "127.0.0.1" or "example.com"
  port: 3306                 # Database server port, default is 3306 for MySQL and MariaDB
  username: "root"           # Database username
  password: "change_me"      # Database password
  database: "app_db"         # Database name to connect
  table_prefix: "x_"         # Every data table prefix

redis_config:
  enabled: false             # Enable redis can access data faster
  host: "127.0.0.1"          # Redis server host, e.g. "127.0.0.1" or "example.com"
  port: 6379                 # Redis server port, default is 6379
  username: ""               # Redis username (usually leave empty)
  password: ""               # Redis password (leave empty if not required)
  database: 0                # Redis database index (default is 0)

runtime:
  mode: "debug"                   # Mode of the Gin application, e.g. "debug" "test" "release"
  jwt_secret: "change_me"         # JWT secret key, must be changed to a random secure string
  access_token_expired_in: 3600   # Access token expiration time in seconds (e.g. 3600 = 1 hour)
  enable_register: true           # If set to "false", will not allow new user register
  min_password_len: 6             # Set the min length of user password allowance
  bcrypt_cost: 16                 # the bcrypt hash of the password at the given cost
  listening_addr: ":8081"         # Application listening port, e.g. ":8080" "172.16.12.120:8081"

illustration:
  save_dir: "./saved"             # The illustration save path, auto create if not existed
  compressed_small_pixel: 720     # Illustration width pixel (small size)
  compressed_medium_pixel: 1280   # Illustration width pixel (medium size)